---
title: "Exploring the LANL Dataset"
author: "Fadel M. Megahed"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_download: TRUE
    number_sections: TRUE
    toc: TRUE
    toc_float: TRUE
    paged_df: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reading the Data in R

```{r r_solution, results='asis'}
if(require(pacman)==F) install.packages('pacman')
pacman::p_load(tidyverse, DT)

# reading the data
# we checked for ?read.csv in console to understand the arguments
lanl_df = read.csv(file = '../data/lanl-auth-dataset-1-03.csv',
                   header = FALSE,
                   skip = 1099999, nrows = 100000)

# data desc for cols
# https://csr.lanl.gov/data/auth/

# cat removes [1] and the quotes
# paste always me to combine my solution and text
# for cat to actually print nicely, we gave the code chunk
# results = 'asis'
cat( paste('The timestamp for observation 1.2M is' ,
      scales::comma(lanl_df[100000, 1]) ) )

# number of unique users
lanl_df$V2 %>% unique() %>% length()
names_unique_users = lanl_df$V2 %>% unique()

# number of unique computers used by user 12 'U12'
# we will use the filter function from dplyr pkg (tidyverse)
lanl_df %>% # also represented as |>
  filter(V2 == 'U12') %>% 
  count(V3) %>%  # they logged into a 123 computers (total rows)
  datatable() # for beautiful printing

lanl_df %>% # also represented as |>
  filter(V2 == 'U12') -> user12

user12$V3 %>% unique() %>% length()
```


# Python

```{r python_setup}
library(reticulate)
py_install("pandas")
```


```{python extract_in_python}
import pandas as pd

df_from_r = r.lanl_df

lanl_pd = pd.read_csv('../data/lanl-auth-dataset-1-03.csv', header = None, skiprows = 1099999,  nrows = 100000)

lanl_pd.tail(n=0)

# number of unique users
lanl_pd.nunique() # we want the answer for col1
lanl_pd[1].nunique()


# number of computers used by U12
lanl_pd[lanl_pd[1]=='U12'][2].nunique()
```

```{r python_to_r}
library(reticulate)
py_df = py$lanl_pd
colnames(py_df) = c('V1', 'V2', 'V3')

setdiff(lanl_df, py_df)
```


