---
title: "Technically Correct, Consistent and ETL"
author: "Fadel M. Megahed"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# KDD Dataset

```{r}
if(!require(tidyverse)) install.packages('tidyverse'); library(tidyverse)
if(!require(skimr)) install.packages('skimr'); library(skimr)
if(!require(DataExplorer)) install.packages('DataExplorer'); library(DataExplorer)
if(!require(pointblank)) install.packages('pointblank'); library(pointblank)

kdd = read_csv(file = '../data/KDDTrain+.csv')

# to quickly get the types of variables and a quick view of
# the first few observations
glimpse(x = kdd) # from the dplyr package ()
skim(kdd) # there is probably a python equivalent to this
DataExplorer::create_report(data = kdd, output_file = 'kdd_report_r.html')


## for example let us convert variables that have only 0 and 1 to factor
## an example for technically correct data

summary_res = summary(kdd)

kdd$label = as.factor(kdd$label)

# mutate is from dplyr --> to create or overwrite exsisting variables
# mutate_if 
kdd = kdd %>% 
  mutate_if(.predicate = is.character, .funs = as.factor)

kdd = kdd %>% 
  mutate( urgent = as.factor(urgent) )
skim(kdd)


# lets talk about consistent data
agent <- 
  create_agent(
    tbl = kdd,
    tbl_name = "kdd_consistency",
    label = "Checking the Consistency of the KDD Dataset"
  ) %>%
  col_is_factor( vars(label, protocol_type, service, flag)) %>%
  col_vals_in_set(vars(label), set = c('normal', 'neptune')) %>% 
  interrogate(sample_limit = nrow(kdd))

```


# Python

```{r installing_pkgs, eval=FALSE}
# run the code below only once
reticulate::py_install('pandas-profiling')
```


To be run in Anaconda, or your favorite Python GUI. Does not work great in RStudio.
```{python, eval = FALSE}
import pandas as pd
from pandas_profiling import ProfileReport

# since pandas profiling is slow
kdd_pd = pd.read_csv('../data/KDDTrain+.csv', nrows = 1000)

# getting the datatypes
kdd_pd.info()

# exploring the data
profile = ProfileReport(kdd_pd, title="Pandas Profiling Report for the KDD Dataset")
profile.to_file("kdd_report_py.html")
```

